name: pypi

on:
  release:
    types: [published]
  
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bump2version
    - name: Create .pypirc file
      run: |
        echo "[pypi]" > ~/.pypirc
        echo "repository = https://upload.pypi.org/legacy/" >> ~/.pypirc
        echo "username = __token__" >> ~/.pypirc
        echo "password = ${{ secrets.PYPI_PASSWORD }}" >> ~/.pypirc
    - name: Check for changes before bumping version
      run: |
        git status
    - name: Bump version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bump2version patch || exit 0  # Exit gracefully if no changes detected
        git status  # Check if changes were made
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .  # Ensure changes are staged
        git commit -m "Bump version"
        git push origin main --tags
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERS }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
